// TASK 88 · the shape of a generated Markdown artifact.
//
// D3 scoped mutation to parsing, joining and validating, on the grounds that mutating render
// templates produces equivalent mutants and noise. That is right about a template's SENTENCES
// and wrong about its SHAPE, and this module is where the distinction becomes checkable.
//
// A blank line in Markdown is not prose — it is syntax. Drop the blank line between a
// paragraph and a table and the table stops rendering. Drop the delimiter row and there is no
// table at all. `renderLedger`'s mutation run left 27 such pushes alive, every one of them
// reading as an equivalent mutant and none of them being one: the ledger's reader is
// `harness-evaluator`, which reads it AS A MARKDOWN DOCUMENT.
//
// So the policy this module makes true, for every render template in lib/ from here on:
//
//   a render template's SENTENCES are noise  -> suppressed at the mutant, with a written reason
//   a render template's SHAPE is structure   -> asserted here, never suppressed
//
// Nothing below quotes a sentence. That is the property that keeps prose free to change
// without touching a test, and it is why this is a shape checker rather than a golden file —
// a fixture regenerated by reflex is a control that stops being read, which is the failure
// `mutation-suppressions.mjs`'s own header records this repository hitting three times.
//
// THE ASSUMPTION, stated rather than discovered later: this checks a GENERATED artifact, in
// which every block-level element is emitted as one line. That is what makes "two adjacent
// paragraph lines are two blocks" correct here and wrong for hand-written prose, which
// soft-wraps. A hand-written document is not what this module is for.
//
// A BLOCK CARRIES NO `kind`, and the first draft's did. Its own mutation run is what removed
// it: `'fence'`, `'list'` and `'paragraph'` were written and never read, so every one of their
// mutants was equivalent by construction — dead data reporting as untested code. A heading was
// a kind too, and it turned out not to be load-bearing either: a heading block and a paragraph
// block are both one line, and the only rule that cares about a heading re-tests the line
// itself. What remains is what is read: where a block starts and where it ends.
//
// Pure — no filesystem access, in the shape the rest of lib/ uses.

const isBlank = (l) => l.trim() === '';
const isFence = (l) => /^\s*(```|~~~)/.test(l);
const isTableRow = (l) => /^\s*\|/.test(l);
const isListItem = (l) => /^\s*([-*+]|\d+\.)\s/.test(l);

/** A table's second row: pipes, dashes, and optional alignment colons. Nothing else. */
const isDelimiterRow = (l) => /^\s*\|(\s*:?-+:?\s*\|)+\s*$/.test(l);

const MESSAGES = {
  'unterminated-fence': 'a fenced block opens here and never closes, so every line after it is unclassifiable and every rule after it would assert nothing (G-13)',
  'document-opens-with-h1': 'the document does not open with a `# ` heading on its first line — a generated artifact with no title, or with a stray value ahead of it, is not the document its reader was handed',
  'table-single-row': 'a table with a single row has no delimiter under its header, so it renders as literal pipes rather than a table',
  'table-delimiter-first': 'this table opens with its delimiter row, so it has no header and does not render as a table',
  'table-missing-delimiter': 'this table has no delimiter row under its header, so it renders as literal pipes rather than a table',
  'document-ends-with-one-blank': 'the document does not end with exactly one blank line — with none, whatever is appended to it joins the last block; with more, a block at the end has gone missing',
};

const finding = (line, rule) => ({ line, rule, message: MESSAGES[rule] });

/**
 * Group the lines into block-level elements: `{ start, end }`, both 0-based line indexes.
 *
 * A block is a run of consecutive table rows, a run of consecutive list items, a fenced region
 * from its opening fence to its closing one, or any other single non-blank line.
 *
 * A fence is consumed WHOLE and its contents are never classified — a `#` inside one is not a
 * heading and a blank line inside one separates nothing. An unterminated fence would swallow
 * the rest of the file, so it is reported and the parse STOPS there: `G-13`'s shape at the
 * level of a checker, since every rule after it would otherwise silently assert nothing about
 * lines nothing could classify.
 */
function readBlocks(lines) {
  const blocks = [];
  let i = 0;

  while (i < lines.length) {
    if (isBlank(lines[i])) { i += 1; continue; }

    if (isFence(lines[i])) {
      const start = i;
      const closes = lines.slice(start + 1).findIndex(isFence);
      if (closes === -1) return { blocks, findings: [finding(start + 1, 'unterminated-fence')] };
      i = start + 1 + closes;
      blocks.push({ start, end: i });
      i += 1;
      continue;
    }

    // A table and a list are the only multi-line blocks with no delimiters of their own: they
    // run until a line stops looking like one. Written as one search over the matching
    // predicate rather than two identical ones, so the run rule is stated once.
    const runs = isTableRow(lines[i]) ? isTableRow : isListItem(lines[i]) ? isListItem : null;
    if (runs) {
      const start = i;
      // The run ends where the predicate stops matching, or at the end of the file. Written as
      // a search over the remaining lines rather than an index loop with a length guard, and
      // the reason is this module's OWN mutation run: past the end every predicate here is
      // false, so a `i < lines.length` bound decided nothing and its mutants were unkillable —
      // an equivalent mutant reporting as untested code, which is what a shape checker exists
      // to stop happening one level up.
      const rest = lines.slice(i);
      const stops = rest.findIndex((l) => !runs(l));
      i += stops === -1 ? rest.length : stops;
      blocks.push({ start, end: i - 1 });
      continue;
    }

    blocks.push({ start: i, end: i });
    i += 1;
  }

  return { blocks, findings: [] };
}

/**
 * Every way the document's shape is broken, in line order.
 *
 * @param {string} text
 * @returns {{line:number, rule:string, message:string}[]}  empty when the shape is sound
 *
 * Four rules here, and a fifth — the unterminated fence — reported by the parse above. Each
 * earns its place by killing a mutant that survived on the real artifact. A sixth was
 * considered and dropped — *every table and list sits under a `##` heading* —
 * because `block-separation` already catches a deleted heading (it leaves two blank lines where
 * one belongs) and a rule with no unique kill is the ceremony `G-10` refuses.
 */
export function markdownShapeFindings(text) {
  const raw = String(text).split(/\r?\n/);
  // The element after the document's final newline is an artifact of splitting, not a line.
  // `split` always yields at least one element, so `lines` is never empty and every index
  // below is safe without a length guard of its own.
  const lines = String(text).endsWith('\n') ? raw.slice(0, -1) : raw;

  const { blocks, findings: parseFindings } = readBlocks(lines);
  const findings = [...parseFindings];

  // R1 · the document opens with an H1, on its first line. One test, and the two guards the
  // first draft wrapped around it are gone: a line matching `^#\s` is non-blank, so it always
  // opens a block at index 0 — which made "no blocks" and "the first block does not start at
  // line 0" both implied by this, and both unkillable. Found by mutation, not by reading.
  if (!/^#\s/.test(lines[0])) findings.push(finding(1, 'document-opens-with-h1'));

  // R2 · exactly one blank line between adjacent blocks. The workhorse: a deleted blank push
  // leaves two blocks touching, and a deleted block push leaves two blanks where one belongs.
  for (let k = 0; k + 1 < blocks.length; k += 1) {
    const gap = blocks[k + 1].start - blocks[k].end - 1;
    if (gap === 1) continue;
    findings.push({
      line: blocks[k + 1].start + 1,
      rule: 'block-separation',
      message: `expected exactly one blank line between this block and the one above it, found ${gap} — with none the two run together and the lower one stops rendering; with more, a block above it has gone missing`,
    });
  }

  // R3 · a table carries a header row and a delimiter row, in that order. Without either, the
  // numbers a reader acts on render as literal pipes. Three distinct rule names rather than one
  // with three messages, so a caller — and a test — can tell them apart without reading prose.
  for (const b of blocks.filter((x) => isTableRow(lines[x.start]))) {
    const rows = lines.slice(b.start, b.end + 1);
    const rule = rows.length < 2 ? 'table-single-row'
      : isDelimiterRow(rows[0]) ? 'table-delimiter-first'
        : !isDelimiterRow(rows[1]) ? 'table-missing-delimiter'
          : null;
    if (rule) findings.push(finding(b.start + 1, rule));
  }

  // R4 · the document closes with exactly one blank line. Stated as one BLANK LINE rather than
  // one newline on purpose: a renderer joining lines and appending a newline legitimately ends
  // with a blank line, and an assertion written the other way fails on correct output — which
  // is how a shape check becomes the thing somebody deletes.
  const last = lines.length - 1;
  if (!isBlank(lines[last]) || (lines.length > 1 && isBlank(lines[last - 1]))) {
    findings.push(finding(lines.length, 'document-ends-with-one-blank'));
  }

  return findings;
}
